/**
 * Data access layer — loads pre-built JSON artifacts at build time.
 * At runtime (browser), these are already inlined by Astro.
 */
import type { Funder, Funding, TravelGrant, Resource, Facets, HomepageFeatured } from './schema'

// These imports work because Astro resolves them at build time.
// The JSON files are generated by the Python build scripts.
import fundersData from '@data/built/funders.json'
import fundingsData from '@data/built/fundings.json'
import travelGrantsData from '@data/built/travel-grants.json'
import resourcesData from '@data/built/resources.json'
import facetsData from '@data/built/facets.json'
import homepageData from '@data/built/homepage-featured.json'

export const funders = fundersData as unknown as Funder[]
export const fundings = fundingsData as unknown as Funding[]
export const travelGrants = travelGrantsData as unknown as TravelGrant[]
export const resources = resourcesData as unknown as Resource[]
export const facets = facetsData as unknown as Facets
export const homepageFeatured = homepageData as unknown as HomepageFeatured

export function getFunderBySlug(slug: string): Funder | undefined {
  return funders.find(f => f.slug === slug)
}

export function getFundingBySlug(slug: string): Funding | undefined {
  return fundings.find(f => f.slug === slug)
}

export function getTravelGrantBySlug(slug: string): TravelGrant | undefined {
  return travelGrants.find(g => g.slug === slug)
}

export function getResourceBySlug(slug: string): Resource | undefined {
  return resources.find(r => r.slug === slug)
}

export function getFunderFundings(funderSlug: string): Funding[] {
  return fundings.filter(f => f.funders.includes(funderSlug) && f.status === 'active')
}

export function getFunderTravelGrants(funderSlug: string): TravelGrant[] {
  return travelGrants.filter(g => g.funders.includes(funderSlug) && g.status === 'active')
}
